<a href="https://colab.research.google.com/github/TatianaO8/AI/blob/master/HW4_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Homework 4 Problem 1

## Problem 1
Using only numpy, implement the function conv2d. It takes as input input_mat and kernel_mat and outputs output_mat. All variables are square matrices. It should compute the convolution of input_mat with the kernel kernel_mat using valid padding.

Note that the size s of the kernel matrix can also be an even number.



In [0]:
import numpy as np

def conv2d(input_mat, kernel_mat):
  s = kernel_mat.shape[0]
  m = input_mat.shape[0]

  # Check for invalid convolution
  if s > m:
    raise Exception('Invalid convolution inputs. The kernel matrix size is greater than the input matrix size.')

  # Calculate the size of the output matrix
  n = m - s + 1

  # Create an empty output matrix
  output_mat = np.zeros((n,n))
  
  for i in np.arange(n):
    for j in np.arange(n):
      for r in np.arange(s):
        for p in np.arange(s): 
          output_mat[i][j] += kernel_mat[r][p] * input_mat[i+r][j+p]
  

  return output_mat

## Testing

The professor mentioned some cases and what the output should be
1. Kernel of 1 by 1 with the value 1 should output the same matrix as the input
2. Kernel of s x s with 0's except with a 1 in the middle should result with an output matrix equal to input matrix with outer cells trimmed away
3. Make sure an exception is thrown when it's an invalid convolution
4. Make sure the right output matrix results when using an even kernel

In [24]:
# 1

input_mat = np.random.rand(3,3)
kernel_mat = np.array([[1]])
output_mat = conv2d(input_mat, kernel_mat)


if np.array_equal(output_mat, input_mat):
  print("Correct output!")
else:
  print("Incorrect output! :(")


Correct output!


In [25]:
# 2

input_mat = np.random.rand(3,3)
kernel_mat = np.array([[0,0,0], [0,1,0], [0,0,0]])
output_mat = conv2d(input_mat, kernel_mat)

print("Input Matrix\n")
print(input_mat)

print("\nOutput Matrix\n")
print(output_mat)

print("\n------------------------------------\n")

input_mat = np.random.rand(6,6)
kernel_mat = np.array([[0,0,0], [0,1,0], [0,0,0]])
output_mat = conv2d(input_mat, kernel_mat)

print("\nInput Matrix\n")
print(input_mat)

print("\nOutput Matrix\n")
print(output_mat)

# As you can see below, the input matrix gets trimmed and that is the output matrix

Input Matrix

[[0.57702806 0.88127725 0.40856339]
 [0.26188931 0.1335019  0.85951477]
 [0.66853553 0.32880108 0.85955845]]

Output Matrix

[[0.1335019]]

------------------------------------


Input Matrix

[[0.2175549  0.65878923 0.95959043 0.89573399 0.97075242 0.93084114]
 [0.79462536 0.55394525 0.60313548 0.39426307 0.63913831 0.85387883]
 [0.34173391 0.35237521 0.86646663 0.0589829  0.72357094 0.84498866]
 [0.83340451 0.87126933 0.33007616 0.86897728 0.4053273  0.61000083]
 [0.63287258 0.04078242 0.55685895 0.10797319 0.76748193 0.0779456 ]
 [0.29742166 0.88636529 0.32358832 0.0777869  0.48792365 0.80551556]]

Output Matrix

[[0.55394525 0.60313548 0.39426307 0.63913831]
 [0.35237521 0.86646663 0.0589829  0.72357094]
 [0.87126933 0.33007616 0.86897728 0.4053273 ]
 [0.04078242 0.55685895 0.10797319 0.76748193]]


In [26]:
# 3

input_mat = np.random.rand(2,2)
kernel_mat = np.array([[0,0,0], [0,1,0], [0,0,0]])
output_mat = conv2d(input_mat, kernel_mat)

# As you can see, an exception is thrown because the kernel matrix size is 3 x 3 while the input matrix is smaller with a size of 2 x 2

Exception: ignored

In [27]:
# 4 

input_mat = np.random.rand(5,5)
kernel_mat = np.array([[1,1], [1,1]])
output_mat = conv2d(input_mat, kernel_mat)

print("Input Matrix\n")
print(input_mat)

print("\nOutput Matrix\n")
print(output_mat)

# You can see that convolution worked even with an even sized kernel matrix

Input Matrix

[[0.74862637 0.52283679 0.18023369 0.09253727 0.29645662]
 [0.25803059 0.63901587 0.07771157 0.93428078 0.41436647]
 [0.75440089 0.49423677 0.70836894 0.66401919 0.63907497]
 [0.47135403 0.13325464 0.35648182 0.27166765 0.11043526]
 [0.28292043 0.87815542 0.54054661 0.08716474 0.15401587]]

Output Matrix

[[2.16850962 1.41979793 1.28476331 1.73764113]
 [2.14568412 1.91933315 2.38438048 2.65174141]
 [1.85324632 1.69234217 2.0005376  1.68519707]
 [1.76568452 1.90843849 1.25586081 0.62328351]]


## Testing

In [28]:
from scipy import signal
import numpy as np

input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0], [0, 1]]))
expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either through an error, or return empty matrix
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append([])



for i in range(len(input_mat)):
  # uncomment line for student code testing
  output_mat = conv2d(input_mat[i], kernel_mat[i])

  # uncomment lines below (and comment line above) for generating test cases.
  if input_mat[i].shape[0] < kernel_mat[i].shape[0]:
    output_mat = []
  else:
    output_mat = signal.convolve2d(input_mat[i], kernel_mat[i], mode='valid')

  print(output_mat)
  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!\n")
  else:
    print("Incorrect output!\n")

[[2 4 2]
 [4 2 4]
 [2 4 2]]
Correct output!

[[2 0 0]
 [0 2 0]
 [0 0 2]]
Correct output!

[[ 1 -1  0]
 [-1  1 -1]
 [ 0 -1  1]]
Correct output!

[[4]]
Correct output!



Exception: ignored