<a href="https://colab.research.google.com/github/TatianaO8/AI/blob/master/HW4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 4 Problem 2

Using only numpy, implement the function maxpooling2d. It takes as input input_mat and s and outputs output_mat. The variables input_mat and output_mat are square matrices and s is an integer. It should compute the maxpooling operation on input_mat using window of shape s times s.

In [0]:
import numpy as np

def maxpooling2d(input_mat, s):
  m = input_mat.shape[0]

  if s > m:
    raise Exception('Invalid maxpooling inputs. s is larger than the input_matrix size.')
  
  n = int(m/s)
  output_mat = np.zeros((n,n))

  for i in np.arange(n):
    for j in np.arange(n):
      output_mat[i][j] = input_mat[i*s][j*s]
      for r in np.arange(s):
        for p in np.arange(s): 
          output_mat[i][j] = max(output_mat[i][j], input_mat[r+i*s][p+j*s])
  
  return output_mat

# Testing some of my own cases


In [12]:
# Throw an exception if s > input_mat size

input_mat = np.random.rand(3,3)
s = 5

output_mat = maxpooling2d(input_mat, s)

Exception: ignored

In [13]:
# Make sure proper padding is being used

input_mat = np.random.rand(5,5)
s = 2
output_mat = maxpooling2d(input_mat, s)

print("Input Matrix\n")
print(input_mat)

print("\nOutput Matrix\n")
print(output_mat)




Input Matrix

[[0.44096043 0.15207888 0.73986526 0.13939079 0.48192007]
 [0.61453799 0.76946117 0.69174068 0.69717942 0.44333853]
 [0.32847673 0.61453923 0.12979949 0.91857544 0.72967603]
 [0.29006581 0.18393076 0.63413741 0.52067901 0.132976  ]
 [0.37560076 0.9789152  0.40288729 0.9076666  0.31041422]]

Output Matrix

[[0.76946117 0.73986526]
 [0.61453923 0.91857544]]


## Testing

In [0]:
import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
  output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")